name: app_anit_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  #State manager
  stacked: ^2.2.5
  stacked_hooks:
  flutter_hooks:

  #stacked_services:
  stacked_services:

  # Navigation
  auto_route:

  # Dependency injection
  get_it:
  injectable: ^1.5.0

  # Other
  logger:
  easy_debounce: ^2.0.1
  uuid: ^3.0.5

  # Flavors
  flutter_dotenv: ^5.0.2

  # Network
  dio: ^4.0.0
  chopper: ^4.0.1
  chopper_api_anit:
    path: chopper_api_anit

  # Database
  shared_preferences: ^2.0.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator: ^1.5.2

  flutter_lints: ^1.0.0



# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - .env

