name: chopper_api_anit
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  chopper: ^4.0.1
  dio: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.6
  chopper_generator: ^4.0.1
  json_annotation: ^4.1.0
  json_serializable: ^4.1.4
  swagger_dart_code_generator: ^2.0.7